### ISSUE TITLE
Docker dev with php 8.3 - Errors with cli

### ISSUE THREAD

**Issue by bernier-db** [ymirapp/cli#39]
Hi!
First of all, I think this project is quite awesome. I already use bref for some laravel projects, and I am quite excited to have the same possibility with wp.

Sadly, I get some errors with the cli. Was able to init the project, but cannot setup either dns zone or ssl. I get this error, though domain is indeed specified (`ymir certificate:request mydomain.com`)
                                        
```
  The Ymir API responded with errors:   
                                        
      * The domains field is required.  
```

I also have a warning saying a new version is available, but I just installed globally using composer (in the container).
`ymir --version` returns Ymir 1.6.2

Here is my dockerfile for development:

```
# Use an official PHP runtime as a parent image
FROM php:8.3-apache

# Set the working directory
WORKDIR /var/www/html

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/


# Install system dependencies
RUN apt-get clean && apt-get update && apt-get install -y \
    git \
    zip \
    unzip \
    curl \
    default-mysql-client

RUN install-php-extensions gd xdebug zip mysqli

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install

# Install Ymir CLI
RUN composer global require ymirapp/cli
RUN export PATH="$PATH:$HOME/.composer/vendor/bin"

# Enable Apache mod_rewrite
RUN a2enmod rewrite

#install wordpress cli
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && \
    mv wp-cli.phar /usr/local/bin/wp

# create dev user
RUN useradd -m -s /bin/bash dev

# Copy the current directory contents into the container at /var/www/html
COPY . /var/www/html

# Make port 80 available to the world outside this container
EXPOSE 80

# Start Apache in the foreground
CMD ["apache2-foreground"]

```

Here is the docker-compose file :

```
version: '3.8'

services:
  web:
    build: ./docker
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=wordpress
    command: /bin/bash -c "apache2-foreground"
  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
```

Any insight would be appreciated, thanks!
